name: todo_app_firestore_example
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0

  # firebase
  firebase_core: ^1.0.3
  cloud_firestore: ^1.0.4

  # slidable
  flutter_slidable: ^0.5.7

  # state management
  provider: ^4.3.2+2
  flutter_local_notifications: ^5.0.0+4
  flutter_datetime_picker: ^1.5.1
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
